# Generated by Django 5.2.7 on 2025-10-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_track',
            old_name='titile',
            new_name='title',
        ),
    ]
