# Generated by Django 5.2.7 on 2025-10-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_tracker', '0002_rename_titile_todo_track_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_track',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('shopping', 'Shopping'), ('vehicle', 'Vehicle')], max_length=20),
        ),
    ]
